[package]
name = "cmus-notify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.152"
id3 = "1.6.0"
lrc = { version = "0.1.7", optional = true }
notify-rust = { version = "4.7.0", features = ["images"] }
regex = "1.7.1"
temp-file = "0.1.7"
typed-builder = "0.12.0"
log = { version = "0.4.17", optional = true }
pretty_env_logger = { version = "0.4.0", optional = true }
thiserror = "1.0.38"

[dependencies.clap]
version = "4.1.4"
features = ["wrap_help", "cargo", "usage", "derive", "suggestions", "color"]

[dependencies.confy]
version = "0.5.1"
default-features = false
features = ["yaml_conf"]

[features]
lyrics = ["lrc"]
debug = ["log", "pretty_env_logger"]

default = ["lyrics", "debug"]

[dev-dependencies]
test-context = "0.1.4"
